[VERSION]
# Found inside CLIENT_INFO.INI in the System.wpk on the SUN client.
CLIENT_VERSION = 2.4.0.3
# Typically found in the bottom left corner of the login/server-select screen on the SUN client. This NEEDS to be checked!
CLIENT_PROTOCOL = 3.4.6
# This is set to the retail SUN launcher and needs to be changed in the future.
LAUNCHER_VERSION = 1.0.9.2

[NETWORK]
# Determines whether one connection per IP address is allowed.
# DEFAULT: TRUE     OPTIONS: TRUE | FALSE
UNIQUE_IP_FILTER = TRUE
# This will force the connection to drop when read or write thread(s) have been idle for x-amount of time. Setting this to 0 will disable the disconnect feature.
# DEFAULT: 300 (5 MINUTES)  VALUE: SECONDS
DISCONNECT = 300

[SECURITY]
# This will force the user
TRUSTED_DEVICES = TRUE

[DATABASE_SERVER]
IP = 127.0.0.1
PORT = 10000

[CLIENT]
IP = 127.0.0.1
PORT = 44405
ACCEPT_THREADS = 2
WORKING_THREADS = 2
BUFFER_SIZE = 4096

[SERVER]
# If IP or PORT has been changed, then please update information in sun-classic database using UpdateServerInfo stored procedure.
IP = 127.0.0.1
PORT = 10001
ACCEPT_THREADS = 2
WORKING_THREADS = 10
BUFFER_SIZE = 4096