[DEACTIVATION]
# X-amount of time that a user has to wait until the DatabaseServer deletes the account and all associated data.
# Setting the value to 0 will tell the database to have the account deleted on the next [DELETION] instance (see below).
# DEFAULT: 30   RANGE: 0-255    UNIT: DAYS
WAIT_TIME = 30

[DELETION]
# X-amount of time the task is initially delayed by the Task Scheduler.
# DEFAULT: 300 (5 MINUTES)    UNIT: SECONDS
INITIAL_DELAY = 300
# The number of time units this task will wait before Task Scheduler runs the task again.
# RANGE: 1 or higher
SCHEDULE_TIME = 1
# The unit of time determined for this task to start again. Spelling matters!
# DEFAULT: DAYS  OPTIONS: MINUTES | HOURS | DAYS
SCHEDULE_TIME_UNIT = DAYS