[DEACTIVATION]
# X-amount of time that a user has to wait until the DatabaseServer deletes the account and all associated data.
# Setting the value to 0 will tell the database to have the account deleted on the next [DELETION] instance (see below).
# DEFAULT: 30   RANGE: 0-255    UNIT: DAYS
WAIT_TIME = 7

[DELETION]
# X-amount of time the task is initially delayed.
# DEFAULT: 0    UNIT: SECONDS
INITIAL_DELAY = 0
# The number of period units this task will wait before starting the task again.
# RANGE: 1 or higher
SCHEDULE_PERIOD = 1
# The unit of time determined for this task to start again. Spelling matters!
# DEFAULT: DAYS  OPTIONS: MINUTES | HOURS | DAYS
SCHEDULE_PERIOD_UNIT = DAYS